#!/usr/bin/env bash
# Quick Reference Guide for hunt.py v2 (Improved)

echo "=========================================="
echo "Hunt.py Quick Reference - v2"
echo "=========================================="
echo ""

echo "1. BASIC USAGE (Default Configuration)"
echo "   python hunt.py --search 'Junior Software Engineer' --location 'Canada'"
echo ""

echo "2. WITH CUSTOM JOB POSITION CONFIG"
echo "   # Backend Developer"
echo "   python hunt.py --search 'Backend Engineer' \\"
echo "     --config job_positions.yaml --position backend"
echo ""
echo "   # Frontend Developer"
echo "   python hunt.py --search 'Frontend Developer' \\"
echo "     --config job_positions.yaml --position frontend"
echo ""
echo "   # Data Scientist"
echo "   python hunt.py --search 'Data Scientist' \\"
echo "     --config job_positions.yaml --position data"
echo ""

echo "3. ADVANCED OPTIONS"
echo "   # Custom output file"
echo "   python hunt.py --out 'results_feb.xlsx'"
echo ""
echo "   # Different number of results per site"
echo "   python hunt.py --results 50"
echo ""
echo "   # Only specific job board"
echo "   python hunt.py --sites 'indeed'"
echo ""
echo "   # Custom resume PDF"
echo "   python hunt.py --resume-pdf '/path/to/resume.pdf'"
echo ""

echo "=========================================="
echo "CONFIGURATION (job_positions.yaml)"
echo "=========================================="
echo ""
echo "Positions available:"
echo "  - backend: Java, Python, SQL, Spring, Docker"
echo "  - frontend: JavaScript, React, TypeScript, CSS, HTML, Vue"
echo "  - data: Python, Statistics, SQL, ML, Data Analysis, R"
echo "  - default: C++, Java, Springboot, SQLite, Statistics, Python"
echo ""
echo "To add new position, edit job_positions.yaml:"
echo "  positions:"
echo "    myposition:"
echo "      skills: ['Skill1', 'Skill2', ...]"
echo "      weights:"
echo "        semantic: 0.40"
echo "        keyword: 0.35"
echo "        title_bonus: 0.15"
echo "        location_bonus: 0.10"
echo ""

echo "=========================================="
echo "SCORING SYSTEM (v2)"
echo "=========================================="
echo ""
echo "Components:"
echo "  1. Semantic Similarity (40%)"
echo "     - Resume vs Job Description embedding similarity"
echo ""
echo "  2. Keyword Matching (35%)"
echo "     - Skills matched via fuzzy matching (75% threshold)"
echo "     - +25 points per skill match (max 100)"
echo ""
echo "  3. Title Bonus (15%)"
echo "     - +15 if title contains: Junior, New Grad, 2025,"
echo "       Entry-Level, Early-Career, Graduate"
echo ""
echo "  4. Location Bonus (10%)"
echo "     - Toronto/Mississauga: +10"
echo "     - Ontario: +5"
echo "     - Other: +0"
echo ""
echo "Formula: (semantic*100*0.40) + (keywords*0.35) + (title*0.15) + (location*0.10)"
echo ""

echo "=========================================="
echo "OUTPUT FILES"
echo "=========================================="
echo ""
echo "job_hunt_results.xlsx (default):"
echo "  - Jobs sheet: Kept positions (sorted by Match_Score DESC)"
echo "  - Filtered_Out sheet: Rejected positions with reasons"
echo ""
echo "Columns in output:"
echo "  - title: Job title"
echo "  - company: Company name"
echo "  - location: Work location"
echo "  - job_url: Link to posting"
echo "  - date_posted: When posted"
echo "  - Target Level: Classification (Perfect Match/Possible/Unlikely)"
echo "  - Match_Score: 0-100 score"
echo "  - Rejection_Reason: Why filtered out"
echo "  - is_remote: Remote job?"
echo "  - salary_range: Salary if available"
echo ""

echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "Issue: Match_Score too low"
echo "  Solution: Lower keyword threshold or increase weight"
echo ""
echo "Issue: Config not loading"
echo "  Solution: pip install pyyaml (for YAML support)"
echo ""
echo "Issue: Semantic model slow"
echo "  Solution: First run downloads model (~30s), then cached"
echo ""
echo "Issue: Resume not found"
echo "  Solution: Set RESUME_PDF env var or place Grace_cs3.pdf in same directory"
echo ""

echo "=========================================="
echo "REQUIREMENTS"
echo "=========================================="
echo ""
echo "pip install -r requirements.txt"
echo ""
echo "Packages:"
echo "  - python-jobspy>=1.1    (job scraping)"
echo "  - pandas>=2.0           (data processing)"
echo "  - openpyxl>=3.1         (Excel output)"
echo "  - pdfplumber>=0.10      (resume extraction)"
echo "  - rapidfuzz>=3.0        (fuzzy matching)"
echo "  - sentence-transformers>=2.0 (semantic similarity)"
echo "  - pyyaml>=6.0           (YAML config, optional)"
echo ""
